#!groovy

// Generated by IBM TransformationAdvisor
// Sat Jan 26 10:28:29 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}